### ISSUE TITLE
Train

### ISSUE THREAD

**Issue by dingyan1478** [alpc91/NICE-GAN-pytorch#22]
Hello, I want to know what is the difference between the network model when light is true or false? It seems that the parameters of FC layer are different in the code, but why is there insufficient display when light is true?
I used my own training set to train. The result test was very poor. Can you give me an answer?
Looking forward to your recovery!

**Comment by alpc91** [comment]
> Hello, I want to know what is the difference between the network model when light is true or false? It seems that the parameters of FC layer are different in the code, but why is there insufficient display when light is true?
> I used my own training set to train. The result test was very poor. Can you give me an answer?
> Looking forward to your recovery!

The attention mechanism of this work is partly inherited from U-GAT-IT. When we were doing this work, because there was not enough GPU memory, it was not set to true. We are very sorry that we cannot answer your doubts directly.
At that time, we felt that the light version was good enough. More learning parameters may not necessarily improve the effect of the model. If you can use the full version and the effect is better, you can use the full version.

**Comment by alpc91** [comment]
> Hello, I want to know what is the difference between the network model when light is true or false? It seems that the parameters of FC layer are different in the code, but why is there insufficient display when light is true?
> I used my own training set to train. The result test was very poor. Can you give me an answer?
> Looking forward to your recovery!

The attention mechanism of this work is partly inherited from U-GAT-IT. When we were doing this work, because there was not enough GPU memory, it was not set to true. We are very sorry that we cannot answer your doubts directly.
At that time, we felt that the light version was good enough. More learning parameters may not necessarily improve the effect of the model. If you can use the full version and the effect is better, you can use the full version.
