### ISSUE TITLE
Do you attempt the selfie2anime datasets? 

### ISSUE THREAD

**Issue by xyxxmb** [alpc91/NICE-GAN-pytorch#7]
I want to know the performance compared with the UGATIT in selfie2anime. Thank you.

**Comment by alpc91** [comment]
UGATIT later released the selfie2anime dataset, so there is no comparison of perfomance.  We later tested it briefly on the selfie2anime dataset, and selfie->anime worked well. You can try the number of iterations and learning rate strategy on this data set and compare the experimental results.

**Comment by xinzi2018** [comment]
i also want to use selfie2anime dataset to train model,  but have some error: 
"RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input."
 I think this is because the matix is too big while FC  in the model  [reference](https://zhuanlan.zhihu.com/p/95883048).but after i set image_size=128 , the problem is stil not solved.

**Comment by alpc91** [comment]
> i also want to use selfie2anime dataset to train model, but have some error:
> "RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input."
> I think this is because the matix is too big while FC in the model [reference](https://zhuanlan.zhihu.com/p/95883048).but after i set image_size=128 , the problem is stil not solved.

Maybe it’s because your pytorch version doesn’t match.
